//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplitApp.Models
{
    using System;
    using System.Collections.Generic;
    using WeSplitApp.ViewModels;

    public partial class Expense : BaseViewModel
    {
        private int _journeyId;
        public int JourneyId { get => _journeyId; set { _journeyId = value; OnPropertyChanged(); } }

        private int _orderNumber;
        public int OrderNumber { get => _orderNumber; set { _orderNumber = value; OnPropertyChanged(); } }

        private int _memberId;
        public int MemberId { get => _memberId; set { _memberId = value; OnPropertyChanged(); } }

        private Nullable<int> _fees;
        public Nullable<int> Fees { get => _fees; set { _fees = value; OnPropertyChanged(); } }

        private string _content;
        public string Content { get => _content; set { _content = value; OnPropertyChanged(); } }

        private Nullable<System.DateTime> _times;
        public Nullable<System.DateTime> Times { get => _times; set { _times = value; OnPropertyChanged(); } }

        public virtual Cost Cost { get; set; }
        public virtual Member Member { get; set; }
    }
}
