//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplitApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int JourneyId { get; set; }
        public int OrderNumber { get; set; }
        public int MemberId { get; set; }
        public Nullable<int> Fees { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Times { get; set; }
    
        public virtual Cost Cost { get; set; }
        public virtual Member Member { get; set; }
    }
}
