//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplitApp.Models
{
    using System;
    using System.Collections.Generic;
    using WeSplitApp.ViewModels;

    public partial class Journey : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journey()
        {
            this.Costs = new HashSet<Cost>();
            this.Photos = new HashSet<Photo>();
            this.Routes = new HashSet<Route>();
            this.Members = new HashSet<Member>();
        }

        private int _id;
        public int Id { get => _id; set { _id = value; OnPropertyChanged(); } }
        
        private Nullable<int> _locationId;
        public Nullable<int> LocationId { get => _locationId; set { _locationId = value; OnPropertyChanged(); } }

        private string _name;
        public string Name { get => _name; set { _name = value; OnPropertyChanged(); } }
        
        private string _description;
        public string Description { get => _description; set { _description = value; OnPropertyChanged(); } }
        
        private Nullable<System.DateTime> _departure;
        public Nullable<System.DateTime> Departure { get => _departure; set { _departure = value; OnPropertyChanged(); } }
        
        private Nullable<System.DateTime> _arrival;
        public Nullable<System.DateTime> Arrival { get => _arrival; set { _arrival = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cost> Costs { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Routes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members { get; set; }
    }
}
