//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplitApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int JourneyId { get; set; }
        public int OrderNumber { get; set; }
        public byte[] ImageBytes { get; set; }
    
        public virtual Journey Journey { get; set; }
    }
}
