//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplitApp.Models
{
    using System;
    using System.Collections.Generic;
    using WeSplitApp.ViewModels;

    public partial class Route : BaseViewModel
    {
        private int _journeyId;
        public int JourneyId { get => _journeyId; set { _journeyId = value; OnPropertyChanged(); } }

        private int _orderNumber;
        public int OrderNumber { get => _orderNumber; set { _orderNumber = value; OnPropertyChanged(); } }

        private string _name;
        public string Name { get => _name; set { _name = value; OnPropertyChanged(); } }

        private string _description;
        public string Description { get => _description; set { _description = value; OnPropertyChanged(); } }

        public virtual Journey Journey { get; set; }
    }
}
